version: '3.5'

services:
  qdrant:
    container_name: acog-qdrant
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./volumes/qdrant/storage:/qdrant/storage
      - ./volumes/qdrant/custom_config.yaml:/qdrant/config/production.yaml

networks:
  default:
    name: acog
